---

#Docker Installed version
docker_compose_version: 1.21.2
docker_ce_version: 18.03.1~ce-0~ubuntu

docker_registry: "{{ vault_docker_registry }}"
docker_user: "{{ vault_docker_user }}"
docker_pwd: "{{ vault_docker_pwd }}"
docker_email: "jenkins@sti.systems"

#Docker Containers Deployed
pull_images: yes #always do a docker pull > since this is dev we want to ge the latest :dev tag ;)
foncier_ui_image_version: dev
foncier_api_image_version: dev
foncier_wf_image_version: "1.8.0"

#Feature Flags
is_swarm_mode_enabled: False
is_datadog_on_docker: True
is_docker_prospector_enabled: True
#start - linked to docker compose vars
db_host: "postgres"
db_port: 5432

db_user: "{{ vault_db_user }}"
db_pass: "{{ vault_db_pass }}"
db_name: ladm

etc_save_hosts:
    - name: "{{ ansible_ssh_host }}"
      ip: 127.0.0.1

# /etc/resolv.conf values
dns_resolv_searchpath:
  - 'az.sogema.local'
  - 'sogema.local' 
  - 'sogema.ca'
  - 'reddog.microsoft.com'

dns_server_list:
  - 192.168.0.70
  - 192.168.1.236
  - 8.8.8.8
  - 8.8.4.4
  - 208.67.222.222


#Docker logs filebeat vars
docker_log_path: "/var/lib/docker/containers/*/*.log"
docker_conatiner_log_name: "fon"

#System logs filebeat vars:
system_log_path: "/var/log/*.log"
