---

#Docker Installed version
docker_compose_version: 1.21.2
docker_ce_version: 18.03.1~ce-0~ubuntu

docker_registry: "{{ vault_docker_registry }}"
docker_user: "{{ vault_docker_user }}"
docker_pwd: "{{ vault_docker_pwd }}"
docker_email: "jenkins@sti.systems"

#Docker Containers Deployed
pull_images: yes #always do a docker pull > since this is dev we want to ge the latest :dev tag ;)
foncier_ui_image_version: dev
foncier_api_image_version: dev
foncier_wf_image_version: "7.8.0"

#Feature Flags
is_swarm_mode_enabled: False
is_datadog_on_docker: True
is_docker_prospector_enabled: True
is_drools_enabled: True

#start - linked to docker compose vars
db_host: "postgres"
db_port: 5432

db_user: "{{ vault_db_user }}"
db_pass: "{{ vault_db_pass }}"
db_name: ladm

#camunda 
camunda_enginerest_url: http://foncier_ui:4200/workflowApi/engine-rest/

#edms - environment
edms_user: foncier@sogematech.com
edms_password: "{{ vault_edms_password }}"
edms_domain: "stisystems.sharepoint.com"
edms_source: "SHAREPOINT"
edms_temp_file_directory: "tempFiles"
edms_sharepoint_site: "/sites/dev.foncier"
edms_sharepoint_folder: "/Documents partages/foncierEdmsDocumentsQA"

#mail - environment
mail_host: "smtp.gmail.com"
mail_port: "587"
mail_username: "sti.foncier@gmail.com"
mail_password: "{{ vault_mail_password }}"
mail_protocol: "smtp"
mail_defaultencoding: "UTF-8"
mail_smtp_auth_enabled: "true"
mail_tls_enabled: "true"

#keycloak - environment
keycloak_auth_server_url: "http://dev-keycloak01.az.sogema.local:8080"
keycloak_realm: "foncier"
keycloak_ssl_required: "external"
keycloak_api_client: "foncier-api"
keycloak_api_client_secret: "95ffe8b6-c466-4f08-ac07-bc938f27115a"
keycloak_api_client_role: "user"

etc_save_hosts:
    - name: "{{ ansible_ssh_host }}"
      ip: 127.0.0.1

# /etc/resolv.conf values
dns_resolv_searchpath:
  - 'az.sogema.local'
  - 'sogema.local' 
  - 'sogema.ca'
  - 'reddog.microsoft.com'

dns_server_list:
  - 192.168.0.70
  - 192.168.1.236
  - 8.8.8.8
  - 8.8.4.4
  - 208.67.222.222


#Docker logs filebeat vars
docker_log_path: "/var/lib/docker/containers/*/*.log"
docker_conatiner_log_name: "fon"

#System logs filebeat vars:
system_log_path: "/var/log/*.log"
