---

#Docker Installed version
docker_compose_version: 1.21.2
docker_ce_version: 18.06.3~ce~3-0~ubuntu

docker_registry: "{{ vault_docker_registry }}"
docker_user: "{{ vault_docker_user }}"
docker_pwd: "{{ vault_docker_pwd }}"
docker_email: "jenkins@sti.systems"
docker_log_driver: "journald"

#Docker Containers Deployed
pull_images: no

#Feature Flags
is_datadog_on_docker: True
is_swarm_mode_enabled: False
is_docker_prospector_enabled: True

#Alfresco Vars - These vars create and pre poluate
edms_data_disk: /datadrive

edms_csrf_filter_origin: https://pp-ml-foncier.sogematech.com
edms_csrf_filter_referer: https://pp-ml-foncier.sogematech.com/.*

alfresco_host: alfresco
alfresco_port: 8080

alfresco_url: http://pp-ml-fon-worker03.az.sogema.local:8380

solr_host: alfresco-solr6
solr_port: 8983

edms_user_first_name: "Foncier"
edms_user_last_name: "Admin"

edms_admin_user: "admin"
edms_admin_password: "{{ vault_edms_admin_password }}"

edms_user: "foncier@sogematech.com"
edms_user_role: "SiteManager"
edms_password: "{{ vault_edms_password }}"

edms_site_id: foncier
edms_site_title: PP-ML Foncier
edms_site_description: "Documents coming from PP-ML Sogema environment"
edms_alfresco_folder: foncierEdmsDocumentsPPML

edms_db_host: alfresco-db
edms_db_port: 5432
edms_db_pass: alfresco

alfresco_xms: 2g
alfresco_xmx: 4g

share_xms: 512m
share_xmx: 1g

solr_xms: 1g
solr_xmx: 2g


etc_save_hosts:
    - name: "{{ ansible_ssh_host }}"
      ip: 127.0.0.1

# /etc/resolv.conf values
dns_resolv_searchpath:
  - 'az.sogema.local'
  - 'sogema.local' 
  - 'sogema.ca'
  - 'reddog.microsoft.com'

dns_server_list:
  - 192.168.0.70
  - 192.168.1.236
  - 8.8.8.8
  - 8.8.4.4
  - 208.67.222.222


#Docker logs filebeat vars
docker_log_path: "/var/lib/docker/containers/*/*.log"
docker_conatiner_log_name: "fon"

#System logs filebeat vars:
system_log_path: "/var/log/*.log"
