---

#Docker Installed version
docker_compose_version: 1.21.2
docker_ce_version: 18.03.1~ce-0~ubuntu

docker_registry: "{{ vault_docker_registry }}"
docker_user: "{{ vault_docker_user }}"
docker_pwd: "{{ vault_docker_pwd }}"
docker_email: "jenkins@sti.systems"

#Docker Containers Deployed
pull_images: no

#Feature Flags
is_datadog_on_docker: True
is_swarm_mode_enabled: False
is_docker_prospector_enabled: True


etc_save_hosts:
    - name: "{{ ansible_ssh_host }}"
      ip: 127.0.0.1

# /etc/resolv.conf values
dns_resolv_searchpath:
  - 'az.sogema.local'
  - 'sogema.local' 
  - 'sogema.ca'
  - 'reddog.microsoft.com'

dns_server_list:
  - 192.168.0.70
  - 192.168.1.236
  - 8.8.8.8
  - 8.8.4.4
  - 208.67.222.222

#Docker logs filebeat vars
docker_log_path: "/var/lib/docker/containers/*/*.log"
docker_container_log_name: "fon"

#System logs filebeat vars:
system_log_path: "/var/log/*.log"


###HAProxy
pem_artifact: "pp-ml-foncier.sogematech.com.pem"

alfresco_host: "pp-ml-fon-worker03.az.sogema.local"
alfresco_port: "8080"

keycloak_host: "dev-keycloak01.az.sogema.local"
keycloak_port: "8080"

ui_host: "pp-ml-fon-worker01.az.sogema.local"
ui_port: "4200"
