---

environment_name: vagrant
ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"

#from Datadog role variables
dd_enabled: yes
datadog_installed: True
dd_process_agent_enabled: False
dd_key: "{{ vault_dd_key }}"

#Host Timezone 
timezone: America/Montreal

etc_save_hosts:
    - name: "{{ ansible_ssh_host }}"
      ip: 127.0.0.1
      
# /etc/resolv.conf values
dns_resolv_searchpath:
  - 'az.sogema.local'
  - 'sogema.local' 

dns_server_list:
  - 8.8.8.8
  - 8.8.4.4
  